apiVersion: v1
kind: Service
metadata:
  labels:
    app: crowd
  name: crowd
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: crowd
  ports:
    - name: crowd-port
      port: 8095
      targetPort: 8095
      protocol: TCP
      nodePort: 30148
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  name: crowd
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crowd
  template:
    metadata:
      labels:
        app: crowd
    spec:
      containers:
      - image: 172.16.16.250/sunyardimg/crowd:201709012
        imagePullPolicy: IfNotPresent
        name: crowd
        ports:
        - containerPort: 8095
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 1G
          requests:
            cpu: 1
            memory: 1G
        volumeMounts:
        - mountPath: /opt/atlassian/crowd-openidserver-webapp/WEB-INF/classes/crowd.properties
          name: openidserverv1-1
          subPath: crowd.properties
        - mountPath: /var/atlassian/crowd
          name: crowdpv
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: openidserverv1.1
            path: crowd.properties
          name: crowdproperties
          optional: false
        name: openidserverv1-1
      - name: crowdpv
        persistentVolumeClaim:
          claimName: crowdpv

