apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: db
  ports:
    - name: db-db-port
      port: 8090
      targetPort: 8090
      protocol: TCP
    - name: db-port
      port: 5432
      targetPort: 5432
      protocol: TCP
      nodePort: 30136
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  name: db
  namespace: kube-system
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: db
  template:
    metadata:
      labels: 
        app: db
    spec:
      containers:
      - image: 172.16.16.250/library/paintedfox_postgresql:20171011_2
        imagePullPolicy: IfNotPresent
        name: db
        ports:
        - containerPort: 5432
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
        volumeMounts:
        - mountPath: /data
          name: crowdpgsql
      restartPolicy: Always
      volumes:
      - name: crowdpgsql
        persistentVolumeClaim:
          claimName: crowdpgsql

