apiVersion: v1
kind: Service
metadata:
  labels:
    app: confluence
  name: confluence
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: confluence
  ports:
    - name: confluence-port
      port: 8090
      targetPort: 8090
      protocol: TCP
      nodePort: 30135

