apiVersion: v1
kind: Service
metadata:
  labels:
    app: gerrit
  name: gerrit
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: gerrit
  ports:
    - name: gerrit-ui
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30181
    - name: gerrit-clone
      port: 29418
      targetPort: 29418
      protocol: TCP
      nodePort: 30191


