kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gerritpv
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
