apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab
  name: gitlab
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
    - name: gitlab-ssh-port
      port: 22
      targetPort: 22
      protocol: TCP
      nodePort: 30187
    - name: gitlab-https-port
      port: 443
      targetPort: 443
      protocol: TCP
      nodePort: 30194
    - name: gitlab-port
      port: 30184
      targetPort: 30184
      protocol: TCP
      nodePort: 30184


