apiVersion: v1
items:
- apiVersion: v1
  data:
    gitlabv1.2: |-
      external_url 'http://172.1.2.44:30184'

      ### OmniAuth Settings
      ###! Docs: https://docs.gitlab.com/ce/integration/omniauth.html
      gitlab_rails['omniauth_enabled'] = true
      gitlab_rails['omniauth_allow_single_sign_on'] = true
      # gitlab_rails['omniauth_sync_email_from_provider'] = 'saml'
      # gitlab_rails['omniauth_sync_profile_from_provider'] = ['saml']
      # gitlab_rails['omniauth_sync_profile_attributes'] = ['email']
      # gitlab_rails['omniauth_auto_sign_in_with_provider'] = 'saml'
      gitlab_rails['omniauth_block_auto_created_users'] = false
      # gitlab_rails['omniauth_auto_link_ldap_user'] = false
      # gitlab_rails['omniauth_auto_link_saml_user'] = false
      # gitlab_rails['omniauth_external_providers'] = ['twitter', 'google_oauth2']
      gitlab_rails['redis_host'] = 'redis'
      gitlab_rails['redis_port'] = 6379
      gitlab_rails['redis_password'] = 'test'
      gitlab_rails['omniauth_providers'] = [
         {
           "name" => "crowd",
           "args" => {
                      "crowd_server_url" => "http://172.1.2.44:30148/crowd",
                      "application_name" => "gitlab",
                      "application_password" => "gitlab"
              }
         }
       ]
  kind: ConfigMap
  metadata:
    labels:
      app: gitlab
    name: gitlabrb
    namespace: kube-system
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""

