apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - name: jenkins-ui
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30139
    - name: gerrit-clone
      port: 50000
      targetPort: 50000
      protocol: TCP


