apiVersion: v1
kind: Service
metadata:
  labels:
    app: jira
  name: jira
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: jira
  ports:
    - name: jira-port
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30134

