apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jira
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira
  template:
    metadata:
      labels:
        app: jira
    spec:
      containers:
      - image: 172.16.16.250/sunyardimg/jira:20170829
        imagePullPolicy: IfNotPresent
        name: jira
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        volumeMounts:
        - mountPath: /opt/jira/atlassian-jira/WEB-INF/classes/crowd.properties
          name: jirapropertiesv1-1
          subPath: crowd.properties
        - mountPath: /opt/jira-home
          name: jirapv
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: jirapropertiesv1.1
            path: crowd.properties
          name: jiracrowdproperties
          optional: false
        name: jirapropertiesv1-1
      - name: jirapv
        persistentVolumeClaim:
          claimName: jirapv

