apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - name: redis-port
      port: 6379
      targetPort: 6379
      protocol: TCP


